





services:
  mysql:
    image: mysql:8
    container_name: mysql-todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notes
      MYSQL_USER: todouser
      MYSQL_PASSWORD: todo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
